name: maven build publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: step 2 Build with Maven & copy artifact
      run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
          
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: rmalewad/springrepo

        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Step 4 - Set up a cache for Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
     
    
          
    
        
    - name: step 5 uploading artifacts to git-artifacts
      uses: actions/upload-artifact@v2
      with:
          name: github-actions-artifact
          path: staging
    
    - name: step 6 Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@master
      with: 
        status: ${{ job.status }}
        notify_when: 'success'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
